name: "CI Tests"

on:
  pull_request:
  push:

env:
  fail-fast: true
  PHPUNIT_FLAGS: "-v"
  SYMFONY_DEPRECATIONS_HELPER: 40

jobs:
  build:
    runs-on: ubuntu-latest
    name: PHP v${{ matrix.php }}, Symfony v${{ matrix.symfony }}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest, php: 7.1, symfony: "4.4.*", composer-flags: '--prefer-stable --prefer-lowest' }
          - { os: ubuntu-latest, php: 7.4, symfony: "4.4.*",composer-flags: '--prefer-stable' }
          - { os: ubuntu-latest, php: 7.4, symfony: "5.4.*",composer-flags: '--prefer-stable' }
          - { os: ubuntu-latest, php: 8.0.2, symfony: "6.0.*", composer-flags: '--prefer-stable' }
          - { os: ubuntu-latest, php: 8.1, symfony: "5.4.*" }
          - { os: ubuntu-latest, php: 8.1, symfony: "6.1.*@dev" }

    steps:
      - uses: actions/checkout@v2
      - name: "Installing php"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl,mbstring,xdebug
          ini-values: date.timezone="Europe/Paris"
          coverage: xdebug
          tools: composer
      - name: Show PHP version
        run: php -v && composer -V
      - name: Download Composer cache dependencies from cache
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Install Symfony ${{ matrix.symfony }}
        run: composer require symfony/symfony:${{ matrix.symfony }} --no-update
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ matrix.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ matrix.os }}-composer-
      - name: Install dependencies
        run: |
          composer update ${{ matrix.composer-flags }} --prefer-dist
      - name: "Run PHPUnit Tests"
        run: "composer test"